version: '3.7'
services:
  api:
    build: .
    image: 'capston-design-be-dev'
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    depends_on:
      - db
      - redis
    networks:
      - api-network
    volumes:
      - ..:/api
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    restart: 'unless-stopped'
    environment:
      - MYSQL_ROOT_PASSWORD=hoplin1234!
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=cloudedu
    volumes:
      - './db:/var/lib/mysql'
    networks:
      - api-network
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
